"""P03: video serving with HTTP Range, GT refusal, judge routes, and sampled frames.

Videos are TEST MEDIA generated by conftest (ffmpeg lavfi testsrc2), not scenario data.
"""

from __future__ import annotations

import json
import re
import shutil
import sys

import pytest

pytestmark = [
    pytest.mark.media,
    pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not on PATH"),
]

CAM_URL = "/media/scenarios/scenario_001/cameras/{}"


@pytest.fixture
def cam_a_bytes(media_root) -> bytes:
    return (media_root / "data/prepared/scenario_001/cam_a.mp4").read_bytes()


async def test_full_video_get_advertises_ranges(client, cam_a_bytes):
    response = await client.get(CAM_URL.format("cam_01"))
    assert response.status_code == 200
    assert response.headers["content-type"] == "video/mp4"
    assert response.headers["accept-ranges"] == "bytes"
    assert response.content == cam_a_bytes


@pytest.mark.parametrize(
    ("header", "start", "end"),
    [("bytes=0-99", 0, 99), ("bytes=100-", 100, None), ("bytes=-50", None, None)],
)
async def test_range_request_returns_206(client, cam_a_bytes, header, start, end):
    size = len(cam_a_bytes)
    if start is None:  # suffix range: the last 50 bytes
        start, end = size - 50, size - 1
    end = size - 1 if end is None else end
    response = await client.get(CAM_URL.format("cam_01"), headers={"Range": header})
    assert response.status_code == 206
    assert response.headers["content-range"] == f"bytes {start}-{end}/{size}"
    assert int(response.headers["content-length"]) == end - start + 1
    assert response.content == cam_a_bytes[start : end + 1]


async def test_unsatisfiable_range_is_416(client, cam_a_bytes):
    size = len(cam_a_bytes)
    response = await client.get(CAM_URL.format("cam_01"), headers={"Range": f"bytes={size}-"})
    assert response.status_code == 416
    assert response.headers["content-range"] == f"bytes */{size}"


async def test_ground_truth_camera_is_forbidden(client):
    response = await client.get(CAM_URL.format("cam_gt"))
    assert response.status_code == 403
    ranged = await client.get(CAM_URL.format("cam_gt"), headers={"Range": "bytes=0-9"})
    assert ranged.status_code == 403


async def test_unknown_camera_or_scenario_is_404(client):
    assert (await client.get(CAM_URL.format("cam_99"))).status_code == 404
    assert (await client.get("/media/scenarios/nope/cameras/cam_01")).status_code == 404


async def test_missing_media_file_is_404(client, settings, scenario_doc):
    scenario_doc["visible_cameras"][0]["file"] = "data/prepared/scenario_001/not_there.mp4"
    (settings.manifests_dir / "scenario_001.json").write_text(json.dumps(scenario_doc))
    assert (await client.get(CAM_URL.format("cam_01"))).status_code == 404
    detail = (await client.get("/api/scenarios/scenario_001")).json()
    assert [c["media_available"] for c in detail["cameras"]] == [False, True, True]


async def test_judge_routes_expose_ground_truth(client, settings, media_root):
    expected = {"event_type": "test_event", "region": "blind_zone_02", "t_event_s": 8.4}
    (settings.prepared_dir / "scenario_001").mkdir(parents=True)
    (settings.prepared_dir / "scenario_001" / "expected.json").write_text(json.dumps(expected))

    judge = (await client.get("/api/judge/scenarios/scenario_001")).json()
    assert judge["judge_only"] is True
    assert judge["ground_truth_camera"]["id"] == "cam_gt"
    assert judge["ground_truth_camera"]["video_url"] == "/api/judge/scenarios/scenario_001/video"
    assert judge["ground_truth_camera"]["video_available"] is True
    assert judge["expected"] == expected

    gt_bytes = (media_root / "data/prepared/scenario_001/hidden_ground_truth.mp4").read_bytes()
    full = await client.get(judge["ground_truth_camera"]["video_url"])
    assert full.status_code == 200 and full.content == gt_bytes
    ranged = await client.get(
        judge["ground_truth_camera"]["video_url"], headers={"Range": "bytes=10-19"}
    )
    assert ranged.status_code == 206
    assert ranged.headers["content-range"] == f"bytes 10-19/{len(gt_bytes)}"
    assert (await client.get("/api/judge/scenarios/nope")).status_code == 404


async def test_judge_expected_is_null_when_absent(client):
    judge = (await client.get("/api/judge/scenarios/scenario_001")).json()
    assert judge["expected"] is None


async def test_sampled_frame_is_served(client, start_run, read_events, settings, make_jpeg):
    run_id = (await start_run())["run_id"]
    await read_events(run_id)
    frame = settings.runs_dir / run_id / "frames" / "cam_01" / "0003.jpg"
    make_jpeg(frame)
    for url in (
        f"/media/runs/{run_id}/frames/cam_01/3.jpg",
        f"/media/runs/{run_id}/frames/cam_01/0003.jpg",
    ):
        response = await client.get(url)
        assert response.status_code == 200
        assert response.headers["content-type"] == "image/jpeg"
        assert response.content == frame.read_bytes()
    assert (await client.get(f"/media/runs/{run_id}/frames/cam_01/4.jpg")).status_code == 404


async def test_frames_after_restart_resolve_from_run_json(
    app, client, start_run, read_events, settings, make_jpeg
):
    run_id = (await start_run())["run_id"]
    await read_events(run_id)
    make_jpeg(settings.runs_dir / run_id / "frames" / "cam_02" / "0000.jpg")
    make_jpeg(settings.runs_dir / run_id / "frames" / "cam_gt" / "0000.jpg")
    app.state.runs._runs.clear()  # simulate a restarted server: run known only on disk
    assert (await client.get(f"/media/runs/{run_id}/frames/cam_02/0.jpg")).status_code == 200
    assert (await client.get(f"/media/runs/{run_id}/frames/cam_gt/0.jpg")).status_code == 403


async def test_frame_route_rejects_traversal_and_ground_truth(
    client, start_run, read_events, settings, make_jpeg
):
    """Each traversal URL has a real JPEG planted where it would resolve, so a missing
    guard shows up as a 200 rather than an accidental 404. Starlette decodes ``%2E``
    and ``%5C`` into path params, so ``..`` and backslashes do reach the handler."""
    run_id = (await start_run())["run_id"]
    await read_events(run_id)
    runs, run_dir = settings.runs_dir, settings.runs_dir / run_id
    base = f"/media/runs/{run_id}/frames"
    planted = {
        f"{base}/cam_gt/0.jpg": (run_dir / "frames/cam_gt/0000.jpg", {403}),
        # camera_id ".." -> <run_dir>/frames/../0000.jpg
        f"{base}/%2E%2E/0.jpg": (run_dir / "0000.jpg", {404}),
        # backslashes separate on Windows: climbs to <runs>/x
        f"{base}/..%5C..%5Cx/0.jpg": (runs / "x/0000.jpg", {404}),
        # escapes the runs dir entirely
        f"{base}/..%5C..%5C..%5Coutside/0.jpg": (runs.parent / "outside/0000.jpg", {404}),
        # run_id ".." with a planted run.json one level above the runs dir
        "/media/runs/%2E%2E/frames/cam_01/0.jpg": (runs.parent / "frames/cam_01/0000.jpg", {404}),
    }
    (runs.parent / "run.json").write_text(json.dumps({"scenario_id": "scenario_001"}))
    for url, (target, allowed) in planted.items():
        make_jpeg(target)
        response = await client.get(url)
        assert response.status_code in allowed, (url, response.status_code)
        assert not re.match(rb"^\xff\xd8", response.content), f"image served for {url}"

    for url, allowed in {
        f"{base}/..%2F..%2Fx/0.jpg": {404},
        f"{base}/cam_01/-1.jpg": {422},
        f"{base}/cam_01/abc.jpg": {422},
        "/media/runs/run_unknown/frames/cam_01/0.jpg": {404},
    }.items():
        assert (await client.get(url)).status_code in allowed, url


async def test_frame_route_refuses_symlink_escape(
    client, start_run, read_events, settings, tmp_path, make_jpeg
):
    run_id = (await start_run())["run_id"]
    await read_events(run_id)
    outside = tmp_path / "outside_frames"
    make_jpeg(outside / "0000.jpg")
    link = settings.runs_dir / run_id / "frames" / "cam_01"
    shutil.rmtree(link, ignore_errors=True)  # the run sampled real frames here
    link.parent.mkdir(parents=True, exist_ok=True)
    try:
        link.symlink_to(outside, target_is_directory=True)
    except OSError:
        if sys.platform != "win32":
            raise
        import _winapi  # unprivileged fallback: a directory junction

        _winapi.CreateJunction(str(outside), str(link))
    response = await client.get(f"/media/runs/{run_id}/frames/cam_01/0.jpg")
    assert response.status_code == 404
